title: Nicholas A. Lee  # your name (or website title) here
logo: # "Exp_PrimaryLogoBlack.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  An Everlearning Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/nicholas-lee-413602194/">LinkedIn</a> 
  <br>
  <a href="mailto:nicholas@lmkwyt.org">Email</a> 
  <br>
  <a href="https://www.rainymood.com/">Rainy Mood</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
